# Generated by Django 4.0.6 on 2022-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeedetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20)),
                ('emp_code', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=10)),
                ('skill', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
